pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    book_thumb:
                        items:
                            -
                                method: grayscale
                                arguments: {  }
                            -
                                method: rotate
                                arguments:
                                    angle: -23
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#FFF'
                            -
                                method: resize
                                arguments:
                                    width: 200
                                    height: 200
                        medias: {  }
                        name: book_thumb
                        description: ''
                        group: ''
                        format: PNG
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1655097058
                        creationDate: 1654756168
                        preserveAnimation: false
