<?php

namespace PIM\ObjectWithVariableDatatypeBundle;

use Pimcore\Extension\Bundle\AbstractPimcoreBundle;

class ObjectWithVariableDatatypeBundle extends AbstractPimcoreBundle
{
    public function getJsPaths()
    {
        return [
            '/bundles/objectwithvariabledatatype/js/pimcore/startup.js'
        ];
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return 'Relation to variable product'; // TODO: Change the autogenerated stub
    }

}
