pimcore:
    staticroutes:
        definitions:
            9cf37cb8-fe17-417d-91f2-1a6494f343fa:
                name: ''
                pattern: ''
                reverse: ''
                controller: null
                variables: ''
                defaults: ''
                siteId: {  }
                methods: {  }
                priority: 0
                creationDate: 1654860125
                modificationDate: 1655794854
