pimcore:
    staticroutes:
        definitions:
            9cf37cb8-fe17-417d-91f2-1a6494f343fa:
                name: book
                pattern: /\/book/
                reverse: ''
                controller: 'App\Controller\DefaultController::defaultAction'
                variables: ''
                defaults: ''
                siteId: {  }
                methods: {  }
                priority: 99
                creationDate: 1654860125
                modificationDate: 1660544210
